### ISSUE TITLE
BDD tests using Ubiquitous Language

### ISSUE THREAD

**Issue by aschrijver** [stackus/ftgogo#1]
A lovely :heart:  project you have created here! I knew about Wild Workouts, but this gives even more detail, fills more blanks. Thank you!

I saw that there are no tests, and this is an example app after all. But one cool concept that is on-topic with the whole DDD theme, is to provide BDD tests and - if possible - formulate them according to the Ubiquitous Language (and understandable for non-technical stakeholders).

Example:

```gherkin
  Feature: Select community member role

    As an organizer who owns and facilitates a community,
    I want to be able to change member roles,
    So that I can select other organizers to facilitate with me.

  Background:
    Given the community is active,
    And the organizer is the community owner.

    # In the MVP community ownership cannot be changed. The
    # creator is the owner.

    Scenario: Change membership role settings
      Given the list of community members,
      And changing members' role settings,
      When I save the role changes,
      Then campaigners can be promoted to organizers,
      And organizers can be demoted to campaigners.
```

An example project that uses BDD in Go (though for a bit more technical features) is https://github.com/trustbloc/orb

(OT: Another thing very cool to test-drive in Go is functional domains. See [Domain Modeling made Functional](https://yewtu.be/watch?v=2JB1_e5wZmU) by Scott Wlaschin)

**Comment by c-nv-s** [comment]
https://github.com/onsi/ginkgo
https://github.com/cucumber/godog

**Comment by aschrijver** [comment]
Awesome @stackus .. did I say you rock before? You rock! :sunglasses:

**Comment by aschrijver** [comment]
Oh, btw, I have no way of contacting you @stackus and don't wanna create a new issue for this. An inspirational video that focuses both on BDD tests, but also (and especially) the process of modeling events can be found here: https://www.youtube.com/watch?v=32lvL_Un8ko

In the video an OAuth2 Golang lib is modeled with DDD + CQRS/ES. May be interesting, esp. since you also have auth now part of the demo project. The code lives here: https://github.com/inklabs/goauth2
